.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-BC\-CHERRY\-PICK" "1" "November 2016" "" ""
.
.SH "NAME"
\fBgit\-bc\-cherry\-pick\fR \- Apply the changes introduced by some existing commits
.
.SH "SYNOPSIS"
\fBgit bc\-cherry\-pick\fR [\fIoptions\fR] \fIcommit\fR
.
.SH "DESCRIPTION"
Given an existing commit, apply the changes it introduced, recording a new commit in the current branch\. This requires your working tree to be clean (no modifications from the HEAD commit)\.
.
.P
The command applies a standard git\-cherry\-pick(1) with the given commit\. It works the same way, except that in case the given commit is a merge, it asks interactively what is the branch to consider in the cherry pick\. By default it does not commit, but only stages the changes, so it allows you to review them\.
.
.P
In case the command can\'t figure out what branch to apply automatically, this is the prompt it presents to you:
.
.IP "" 4
.
.nf

This is a merge commit
Select one option to review the state or the branch to apply:
    graph)      review the commit graph
    commits)    review the list of commits
    diff)       review the diff
    1|2)        select the branch to be applied (1 or 2)
    help)       show this message
    quit)       abort

Selection (<NUM>/g/c/d/h/q)
.
.fi
.
.IP "" 0
.
.P
Options \fBgraph\fR, \fBcommits\fR and \fBdiff\fR gives an overview of the branches to be considered, \fB1\fR selects the first branch and \fB2\fR the second one\. Option \fBq\fR is to abort the cherry\-pick\.
.
.P
If conflicts arise, you will need to resolve them by editing the files and adding them with git\-add(1) and continue the cherry\-pick with git\-cherry\-pick(1) with the \fB\-\-continue\fR option\. You can use git\-status(1) to be guided through this process\.
.
.SH "OPTIONS"
.
.TP
\fB\-n\fR, \fB\-\-no\-commit\fR
Stage changes if the cherry\-pick succedes, but do not commit\.
.
.TP
\fB\-\-dry\-run\fR
Do not actually execute the git commands, but only print them\.
.
.TP
\fB<commit>\fR
The SHA\-1 identifier of the commit to use for the cherry\-pick\. See gitrevisions(7)\. This parameter is mandatory\.
.
.SH "EXAMPLES"
Suppose to have this history:
.
.IP "" 4
.
.nf

     \.\-\-\-B\-\-\-C\-\-\-D\-\-\-
    /   /       /
\-\-\-A   /       /
    \e /       /
     E\-\-\-\-\-\-\-F

\-\-\-G\-\-\-H
.
.fi
.
.IP "" 0
.
.P
The commits are:
.
.IP "\(bu" 4
A is the common ancestor between two branches\.
.
.IP "\(bu" 4
Commits B, C, D are part of the master branch\.
.
.IP "\(bu" 4
Commits E, F are part of a feature branch\.
.
.IP "\(bu" 4
Commits B and D are merge commits between the two branches\. They are however different, because D is a normal merge bringing together commits B, C and F, while B has been created with \fB\-\-ff\-only option\fR, so even if master hasn\'t changed in the meantime, instead of fast forwarding master to E, a new merge commit has been created\.
.
.IP "\(bu" 4
Commits G, H are commits of a release branch (H is its last commit)\.
.
.IP "" 0
.
.P
You want to cherry pick onto the release branch one of the commits in the other two branches\. The other two branches are not affected\. The end result for the release branch will be this in all the examples:
.
.IP "" 4
.
.nf

\-\-\-G\-\-\-H\-\-\-I
.
.fi
.
.IP "" 0
.
.P
If you want to cherry\-pick the commit F:
.
.IP "" 4
.
.nf

$ git bc\-cherry\-pick F

The command will simply cherry pick the commit and create I, without user
interaction\.
.
.fi
.
.IP "" 0
.
.P
If you want to cherry\-pick the commit B:
.
.IP "" 4
.
.nf

$ git bc\-cherry\-pick B

The command will simply cherry pick the commit and create I, without user
interaction\. This is possible because she branch to select is unambiguosly
the one containing E, since the other one is empty (i\.e\. there are no
commits between A (common ancestor) and B\.
.
.fi
.
.IP "" 0
.
.P
If you want to cherry\-pick the commit D, with the commits introduced in the feature branch:
.
.IP "" 4
.
.nf

$ git bc\-cherry\-pick D

The command will stop and ask for user interaction, because it doesn\'t know
which branch to apply\. The choice is between commits E, F, or B, C\. In this
case we want E, F\. To help us on selecting the branch we can review their
contents by selecting `c` in the prompt\. The outupt will be this:

Branch 1:
C message 2
B message 1

Branch 2:
E message 3
F message 4

In this case we need to input `2` to select the second branch\.
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
git\-cherry\-pick(1)
